language: c
sudo: false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget https://downloads.arduino.cc/arduino-1.6.12-linux64.tar.xz
  - tar xf arduino-1.6.12-linux64.tar.xz
  - mv arduino-1.6.12 $HOME/arduino_ide
  # Make sure the Arduino command is added to the path
  - export ARDUINO_HOME="$HOME/arduino_ide"
  - export ARDUINO_LIBS="$ARDUINO_HOME/libraries"
  - export PATH="$ARDUINO_HOME:$PATH"
install:
#  - ln -s $PWD /usr/local/share/arduino/libraries/WiFiManager
# boards manager not working on 1.6.7 - 1.6.8
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
# install lib arduino json not working in 1.6.5
#  - arduino --install-library "ArduinoJson"
  - git clone https://github.com/markruys/arduino-DHT.git $ARDUINO_LIBS/arduino-DHT
  - git clone https://github.com/tzapu/WiFiManager.git $ARDUINO_LIBS/WiFiManager
  - git clone https://github.com/bblanchon/ArduinoJson $ARDUINO_LIBS/ArduinoJson
# Removing "Spurious" directory from ArduinoJson
  - rm -rf $ARDUINO_LIBS/ArduinoJson/.github
  - arduino --install-boards esp8266:esp8266
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref "compiler.warning_level=default" --save-prefs
  - mv config.example.h config.h
  - sleep 3
script:
  # Temporary check to break the build
  - exit 1
  # - "echo $ARDUINO_HOME"
  # - "echo $ARDUINO_LIBS"
  # - "echo $PWD"
  # - "echo $HOME"
  # - "ls $PWD"
# Check for Generic ESP-01 Module
  - arduino --verify --board esp8266:esp8266:generic:FlashSize=512K64 $PWD/esp8266-dht22-sleeper-node.ino
# Try and see if we can check for the d1_mini too
  - arduino --verify --board esp8266:esp8266:d1_mini:FlashSize=4M1M $PWD/esp8266-dht22-sleeper-node.ino
#  - arduino -v --verbose --verify --board esp8266:esp8266:generic $PWD/esp8266-dht22-sleeper-node.ino
#  - source $TRAVIS_BUILD_DIR/travis/common.sh
#  - build_examples
#  - "cat $PWD/examples/AutoConnect/AutoConnect.ino"
#  - arduino -v --verbose-build --verify $PWD/examples/AutoConnect/AutoConnect.ino
#  - arduino --verify --board arduino:avr:uno $PWD/examples/IncomingCall/IncomingCall.ino
#  - arduino --verify --board arduino:avr:uno $PWD/examples/AdafruitIO_GPS/AdafruitIO_GPS.ino
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - secure: "HYIPxBbbbx/JOFkMjmKI/oY7sO2TIYbUA/uVcoGg9Y/V9kHxUOiR0qAWJn0aMes9XTQDBuYkB7ZijqSFhpKTs3BIyEgdX97rbWvNaZpo5Z+jbIw+C9cAlC/i4GaWtDx7ICHowUNaGXmLAI7usnxo5MyTmdpuze/XYIfpX4GyCOXOEgxU1wCEf4W/q8JKY6qqVzsKAW2D5HG2Dr1VU4XqNC+4Ml5+qfQSCjYl/YcTNAoaZmS4e2IDepaYQrbU8W1PlM+LU3ssegImrH9tZ9IV8tbSR8SNwSNoMektD0QLNXaoOilBEALP3BQ+AtY2LYErwG39X81RIu0CETHuDQNApORJGPz9Ww1sibtYSaRrg7a4VjMeY3/klnQSHR/yovIxKhpnUx3/qVlALH5ZAHtRsVkNrelwhYb8c+cvox/x1S887/T34b+UbZF/2N90Q9qTtyapg1I1i/bfKwqcO1R+ygvqqlO1igf9jcReEoaALmaCtHmpwj/N9C2PTrt/rYkkbksnpK8le9A3DLLrrWG2e55u5hxf2QwpI3w7ei+EAvtIY5/VHthbiyKP0ollzEh4FrCQymORuZ7cr6I0Rk/ebP8Ubx67uF9EYUF7Iv1/40cbKXcrgKTUDPxUb0ytWSvVbuhbPp79AmocVYzTxtRXcDoJDLePVNXO/d1ZK9SXcHo="
      - secure: "XF5UAI+6IbfN7FqhyjRg1IFn01MI6Jb2qkkDUBrlfx6VCyI5B/mJekYlQVZ29/QPss9JPuGXe/m2+JQnWWqJiR5lP9sd12iJnTX6mijDgqdE5i1pqXfknprUX4keYcycGENOUjRZoZ1y7qMrO3Odrvh4FtfItnlkJ2kIzITVuBvsdYbURv38HjAyCTTNRgQtceLtoRqHQ3ryOMAnHz1XMymteTW68hy67P8uFDrWFiqJo3WGY73cTvPYI9aM6yNyc7QYJyoTnwV+es7D9xYEk2wclVdZlpegVuXzBnHuZzUeLFbEArOrpfDezo8ihWamX6DLa0/H4k4S7rocAC8xnzDufesuILg8aaclrEpn0seruKaefSA46bCDdkve+bA2OFmXqjhAEvyquJDlBRqGBXTav+c5JtaOnItdCIxAxCSzvsFrwh5JhpV7+j9YvFG4FFLdE4HCxbYssatRc8j+7D0nKnmWvCOjVoR3TWi2ffg8wlnXhEuc3ymLPsAHk7zOMIPXBFQ5FEOYx92PngIk+dIViZqfIbRyaPeMSu+Bdrf+fYXXcwLmRV2A7VgqXevt4dVDXmXIUUwbtyVzaaCcZovzEUeUR6PdPZLZ20vy+qF0z6YpDQO1wOBERqzIkLkjdycSkStvUIPjNDHsEdH1pN2IXOegBBjXLm7ZZ6awkM0="
    on_success: change
    on_failure: always
