language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/thomasvnl/esp8266-dht22-sleeper-node/master/travis/install.sh)
install:
  - arduino --install-library "Adafruit Unified Sensor,DHT sensor library"
script:
  - build_platform esp8266
notifications:
  email:
    on_success: change
    on_failure: change
